---
version: "3"
services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "catalog"
    ports:
    - "5432:5432"
  redisearch:
    image: "redislabs/redisearch:latest"
    ports:
    - "6379:6379"
