spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/catalog
        password: postgres
        username: postgres
    flyway:
        enabled: true
        url: jdbc:postgresql://localhost:5432/catalog
        password: postgres
        user: postgres
        locations:
            - classpath:db/migration
        validate-migration-naming: true
