---
app:
  db:
    host: "localhost:5432"
  redis:
    host: "localhost"
    port: 6379
    db: 0
server:
  port: 8080
  netty:
    connection-timeout: "10s"
    idle-timeout: "10s"
spring:
  task:
    execution:
      thread-name-prefix: "task-pool-"
      pool:
        core-size: 1
        max-size: 1
        queue-capacity: 1000
        keep-alive: "10s"
        allow-core-thread-timeout: true
  webflux:
    base-path: "/"
  jpa:
    open-in-view: false
  r2dbc:
    url: "r2dbc:postgresql://${app.db.host}/catalog"
    password: "postgres"
    username: "postgres"
  flyway:
    enabled: true
    url: "jdbc:postgresql://${app.db.host}/catalog"
    password: "postgres"
    user: "postgres"
    locations:
    - "classpath:db/migration"
    validate-migration-naming: true
redis:
  host: "${app.redis.host}"
  port: "${app.redis.port}"
  db: "${app.redis.db}"
