---
app:
  db:
    host: "localhost:5432"
  redis:
    host: "localhost"
    port: 6379
    db: 0
spring:
  jpa:
    open-in-view: false
  r2dbc:
    url: "r2dbc:postgresql://${app.db.host}/catalog"
    password: "postgres"
    username: "postgres"
  flyway:
    enabled: true
    url: "jdbc:postgresql://${app.db.host}/catalog"
    password: "postgres"
    user: "postgres"
    locations:
    - "classpath:db/migration"
    validate-migration-naming: true
redis:
  host: "${app.redis.host}"
  port: "${app.redis.port}"
  db: "${app.redis.db}"
