name: Java + Maven + Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: setup mvnd
      run <:
        curl https://downloads.apache.org/maven/mvnd/0.8.2/maven-mvnd-0.8.2-linux-amd64.zip -o maven-mvnd-0.8.2-linux-amd64.zip &&
        unzip maven-mvnd-0.8.2-linux-amd64.zip &&
        export PATH=$PATH:$(pwd)/maven-mvnd-0.8.2-linux-amd64/bin
    - name: check formatting
      run: mvnd spotless:check
    - name: build
      run: make
