name: Java + Maven + Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
    - name: fmt check
      run: mvn spotless:check
    - name: build
      run: mvn install
    - name: spotbugs
      run: mvn spotbugs:spotbugs
    - name: docker
      run: docker buildx build . -t catalog
