name: Java + Maven + Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: setup mvnd
      run: sdk install mvnd
    - name: check formatting
      run: mvnd spotless:check
    - name: build
      run: make
