---
name: "Java + Maven + Docker"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Set up JDK 19"
      uses: "actions/setup-java@v3"
      with:
        java-version: "19"
        distribution: "zulu"
    - name: "git"
      run: "git clone https://github.com/BenSlabbert/json-writer /tmp/json-writer"
    - name: "install deps"
      run: "mvn -f /tmp/json-writer install"
    - name: "make"
      run: "make"
